apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-domain-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  knowledge_engine.yaml: |
{{ .Values.domainConfig | indent 4 }}
