apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dpg-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  dpg.yaml: |
{{ .Values.dpgConfig | indent 4 }}
