image:
  repository: jaegertracing/all-in-one
  tag: "1.55"
  pullPolicy: IfNotPresent
service:
  uiPort: 16686
  grpcPort: 14250
  otlpGrpcPort: 4317
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi
