apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-domain-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    layer: domain-config
data:
  domain.yaml: |
{{ .Values.config | toYaml | indent 4 }}
