"""Tests for the wizard's recording phase helper (collect_recording_settings).

The Configuration Agent wizard is schema-driven (React UI → JSON dict → wizard
backend); there is no interactive ``_prompt`` helper.  ``collect_recording_settings``
therefore accepts a pre-collected dict and fills in missing / blank values with
safe defaults — the function is called from the wizard's reach-phase handler
after the UI has gathered operator input.
"""
import pytest


class TestCollectRecordingSettingsDisabled:
    """When operator chooses 'disabled', no other fields are gathered."""

    def test_disabled_returns_minimal_dict(self):
        from dev_kit.agent.tools import collect_recording_settings

        out = collect_recording_settings({"source": "disabled"})
        assert out["source"] == "disabled"
        # Should NOT include full sub-fields — keep the block minimal.
        assert set(out.keys()) == {"source"}

    def test_missing_source_defaults_to_disabled(self):
        from dev_kit.agent.tools import collect_recording_settings

        out = collect_recording_settings({})
        assert out["source"] == "disabled"
        assert set(out.keys()) == {"source"}

    def test_none_source_treated_as_disabled(self):
        from dev_kit.agent.tools import collect_recording_settings

        out = collect_recording_settings({"source": None})
        assert out["source"] == "disabled"


class TestCollectRecordingSettingsSaltAutoGenerate:
    """Empty or missing salt must trigger autogeneration (>= 32 chars)."""

    def test_empty_salt_autogenerated(self):
        from dev_kit.agent.tools import collect_recording_settings

        out = collect_recording_settings({"source": "vobiz", "caller_id_hash_salt": ""})
        salt = out.get("caller_id_hash_salt", "")
        assert len(salt) >= 32, f"expected autogenerated salt >=32 chars, got {len(salt)}"

    def test_missing_salt_autogenerated(self):
        from dev_kit.agent.tools import collect_recording_settings

        out = collect_recording_settings({"source": "vobiz"})
        salt = out.get("caller_id_hash_salt", "")
        assert len(salt) >= 32

    def test_short_salt_replaced(self):
        """A salt shorter than 32 chars must be replaced by autogenerated value."""
        from dev_kit.agent.tools import collect_recording_settings

        out = collect_recording_settings({"source": "vobiz", "caller_id_hash_salt": "short"})
        salt = out.get("caller_id_hash_salt", "")
        assert len(salt) >= 32

    def test_valid_salt_preserved(self):
        """A salt with >= 32 chars must NOT be replaced."""
        from dev_kit.agent.tools import collect_recording_settings

        provided = "A" * 64
        out = collect_recording_settings({"source": "vobiz", "caller_id_hash_salt": provided})
        assert out["caller_id_hash_salt"] == provided

    def test_two_autogenerated_salts_differ(self):
        """Each call should produce a fresh random salt (not a constant)."""
        from dev_kit.agent.tools import collect_recording_settings

        a = collect_recording_settings({"source": "vobiz"})["caller_id_hash_salt"]
        b = collect_recording_settings({"source": "vobiz"})["caller_id_hash_salt"]
        assert a != b


class TestCollectRecordingSettingsS3:
    """Backend=s3 path must preserve bucket/prefix/region fields."""

    def test_s3_fields_preserved(self):
        from dev_kit.agent.tools import collect_recording_settings

        out = collect_recording_settings({
            "source": "vobiz",
            "caller_id_hash_salt": "X" * 64,
            "store": {
                "backend": "s3",
                "s3": {"bucket": "my-bucket", "prefix": "rec/", "region": "ap-south-1"},
            },
        })
        assert out["store"]["backend"] == "s3"
        assert out["store"]["s3"]["bucket"] == "my-bucket"
        assert out["store"]["s3"]["prefix"] == "rec/"
        assert out["store"]["s3"]["region"] == "ap-south-1"

    def test_local_defaults_when_no_store(self):
        from dev_kit.agent.tools import collect_recording_settings

        out = collect_recording_settings({"source": "vobiz", "caller_id_hash_salt": "X" * 64})
        assert out["store"]["backend"] == "local"
        assert out["store"]["local"]["base_path"] == "/var/recordings"

    def test_s3_kms_defaults_to_empty(self):
        from dev_kit.agent.tools import collect_recording_settings

        out = collect_recording_settings({
            "source": "vobiz",
            "caller_id_hash_salt": "X" * 64,
            "store": {"backend": "s3", "s3": {"bucket": "b"}},
        })
        assert out["store"]["s3"]["kms_key_id"] == ""


class TestCollectRecordingSettingsEdgeCases:
    """Edge-case and error-handling scenarios."""

    def test_invalid_existing_type_raises_value_error(self):
        from dev_kit.agent.tools import collect_recording_settings

        with pytest.raises(ValueError, match="must be a dict"):
            collect_recording_settings("not-a-dict")  # type: ignore[arg-type]

    def test_full_opted_in_output_has_required_keys(self):
        from dev_kit.agent.tools import collect_recording_settings

        out = collect_recording_settings({"source": "vobiz"})
        for key in ("source", "consent_purpose", "webhook_timeout_s", "fetch_timeout_s",
                    "min_duration_ms", "caller_id_hash_salt", "store"):
            assert key in out, f"missing key: {key}"
